"""empty message

Revision ID: b79a287095cb
Revises: 5f477099d66c
Create Date: 2018-08-17 07:03:19.841012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b79a287095cb'
down_revision = '5f477099d66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_prov',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_kab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=45), nullable=True),
    sa.Column('id_prov', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prov'], ['tb_prov.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_kec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=45), nullable=True),
    sa.Column('id_kab', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kab'], ['tb_kab.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_desa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=45), nullable=True),
    sa.Column('id_kec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kec'], ['tb_kec.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_dusun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=45), nullable=True),
    sa.Column('id_desa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_desa'], ['tb_desa.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tb_alamat', sa.Column('id_dusun', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_alamat', 'tb_dusun', ['id_dusun'], ['id'], ondelete='cascade')
    op.drop_column('tb_alamat', 'prov')
    op.drop_column('tb_alamat', 'kec')
    op.drop_column('tb_alamat', 'desa')
    op.drop_column('tb_alamat', 'kab')
    op.drop_column('tb_alamat', 'dusun')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_alamat', sa.Column('dusun', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('tb_alamat', sa.Column('kab', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('tb_alamat', sa.Column('desa', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('tb_alamat', sa.Column('kec', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('tb_alamat', sa.Column('prov', mysql.VARCHAR(length=200), nullable=True))
    op.drop_constraint(None, 'tb_alamat', type_='foreignkey')
    op.drop_column('tb_alamat', 'id_dusun')
    op.drop_table('tb_dusun')
    op.drop_table('tb_desa')
    op.drop_table('tb_kec')
    op.drop_table('tb_kab')
    op.drop_table('tb_prov')
    # ### end Alembic commands ###
